### ISSUE TITLE
`npm test` fails due to influx npm and InfluxDB version mismatch

### ISSUE THREAD

**Issue by ottumm** [amcgee/remjs#5]
https://travis-ci.org/amcgee/remjs/jobs/77768511

**Comment by ottumm** [comment]
Looks like an InfluxDB issue:

```
  168 passing (3s)
  5 failing

  1) nedb::REM InfluxDB functionality. fetch some data:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:944:16

  2) nedb::REM InfluxDB functionality. fetch some data:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:944:16

  3) nedb::REM InfluxDB functionality. test limiting:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:944:16

  4) nedb::REM InfluxDB functionality. test skipping (unimplemented, but should succeed):
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:944:16

  5) nedb::REM InfluxDB functionality. test sorting (unimplemented, but should succeed):
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at _stream_readable.js:944:16
```

**Comment by ottumm** [comment]
I believe this is because we are using an older version of the influx npm package (3.2.0) and a newer version of InfluxDB. 

From https://www.npmjs.com/package/influx:

> Version 3.x.x is compatible with InfluxDB 0.8.x
> 
> Version 4.x.x is compatible with InfluxDB 0.9.x
